<?php 
define("DB_HOST",'localhost');//主机URL
define("DB_USER",'root');//用户名
define('DB_PWD','123456');//密码
define('DB_NAME','dsqc');//数据库名
define('DB_PORT','3306');//端口
define('DB_TYPE','mysql');//数据库类型
define('DB_CHARSET','utf8');//字符编码
?>